name: Basic workflow
on:
  push:

jobs:
  environment: prod
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: 21
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Echo SPORTMONKS_API_TOKEN
        run: echo "sportmonks.api.token=${{ secrets.SPORTMONKS_API_TOKEN }}" > src/main/resources/token.properties
      - name: Build project
        run: ./gradlew build