name: Basic workflow
on:
  push:

jobs:
  qa:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: unit tests
        run: ./gradlew test