name: CI Workflow
on:
  push:
    branches: ['main']
    paths:
      - '.github/workflows/**'
      - 'src/main/**'
      - 'build.gradle'
  pull_request:
    branches: ['main']
    paths:
      - '.github/workflows/**'
      - 'src/main/**'
      - 'build.gradle'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  ENCRYPTION_PASSWORD: ${{ secrets.ENCRYPTION_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v3
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: 21
      - name: Build project
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: build
        env:
          ACTOR: ${{ github.actor }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Set services for integration tests
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: docker-compose.yml
      - name: Run integration tests
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: integrationTests
      - name: Upload jar
        if: github.ref == 'refs/heads/main' && (
              contains(github.event.head_commit.modified, 'src/main/') ||
              contains(github.event.head_commit.added, 'src/main/') ||
              contains(github.event.head_commit.removed, 'src/main/') ||
              contains(github.event.head_commit.modified, 'build.gradle') ||
              contains(github.event.head_commit.added, 'build.gradle') ||
              contains(github.event.head_commit.removed, 'build.gradle')
            )
        uses: actions/upload-artifact@v4
        with:
          name: jar-artifact
          path: build/libs
  build-and-push-image:
    if: github.ref == 'refs/heads/main' && (
          contains(github.event.head_commit.modified, 'src/main/') ||
          contains(github.event.head_commit.added, 'src/main/') ||
          contains(github.event.head_commit.removed, 'src/main/') ||
          contains(github.event.head_commit.modified, 'build.gradle') ||
          contains(github.event.head_commit.added, 'build.gradle') ||
          contains(github.event.head_commit.removed, 'build.gradle')
        )
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: jar-artifact
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
      - name: Delete jar artifact
        uses: geekyeggo/delete-artifact@v5
        with:
          name: jar-artifact