name: CI Workflow
on:
  push:
    branches: ['main']
    paths:
      - '.github/workflows/**'
      - 'src/main/**'
      - 'build.gradle'
  pull_request:
    branches: ['main']
    paths:
      - '.github/workflows/**'
      - 'src/main/**'
      - 'build.gradle'

jobs:
  call-ci:
    uses: moravianblackcat/cicd/.github/workflows/ci.yml@main